server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kiangNg/aispringcloud.git
          search-paths: config
          username: kiangNg
          password: wjy18163202088
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/